CREATE TABLE "MYTHIC_RECORD"
(
    "RECORD_ID" VARCHAR2(100) NOT NULL,
    "JSON_TEXT" BLOB NOT NULL,
    CONSTRAINT "MYTHIC_RECOERD_PK" PRIMARY KEY ("RECORD_ID")
)
;
CREATE TABLE "MYTHIC_RECORD_PLAYER"
(
    "RECORD_ID" VARCHAR2(100) NOT NULL,
    "PLAYER_REALM" VARCHAR2(20) NOT NULL,
    "PLAYER_NAME" VARCHAR2(100) NOT NULL,
    CONSTRAINT "MYTHIC_RECOERD_PLAYER_PK" PRIMARY KEY ("RECORD_ID","PLAYER_REALM","PLAYER_NAME")
)
;
CREATE TABLE "MYTHIC_BOTUSER"
(
    "USER_ID" VARCHAR2(20) NOT NULL,
    "WEB_SESSION_ID" VARCHAR2(100) NOT NULL,
    CONSTRAINT "MYTHIC_BOTUSER_PK" PRIMARY KEY ("USER_ID")
)
;
CREATE TABLE "MYTHIC_BOTUSER_PLAYER"
(
    "USER_ID" VARCHAR2(20) NOT NULL,
    "PLAYER_REALM" VARCHAR2(20) NOT NULL,
    "PLAYER_NAME" VARCHAR2(100) NOT NULL,
    CONSTRAINT "MYTHIC_BOTUSER_PLAYER_PK" PRIMARY KEY ("USER_ID","PLAYER_REALM","PLAYER_NAME")
)
;
CREATE TABLE "MYTHIC_BOTUSER_COMMENT"
(
    "USER_ID" VARCHAR2(20) NOT NULL,
    "PLAYER_REALM" VARCHAR2(200) NOT NULL,
    "PLAYER_NAME" VARCHAR2(100) NOT NULL,
    "COMMENTS" VARCHAR2(1000) NOT NULL,
    CONSTRAINT "MYTHIC_BOTUSER_COMMENT_PK" PRIMARY KEY ("USER_ID","PLAYER_REALM","PLAYER_NAME")
)
;
DROP TABLE "MYTHIC_AUCTION";
CREATE TABLE "MYTHIC_AUCTION"
(
    "AUCTION_ID" NUMBER(20) NOT NULL,
    "REALM_ID" NUMBER(20) NOT NULL,
    "ITEM_ID" VARCHAR2(200) NOT NULL,
    "FIRST_SEEN_TS" NUMBER(20) NOT NULL,
    "LAST_SEEN_TS" NUMBER(20) NOT NULL,
    "JSON_TEXT" CLOB NOT NULL,
    CONSTRAINT "MYTHIC_AUCTION_PK" PRIMARY KEY ("AUCTION_ID")
)
;
DROP TABLE "MYTHIC_ITEM";
CREATE TABLE "MYTHIC_ITEM"
(
    "ITEM_ID" VARCHAR2(200) NOT NULL,
    "JSON_TEXT" CLOB NOT NULL,
    CONSTRAINT "MYTHIC_ITEM_PK" PRIMARY KEY ("ITEM_ID")
)
;
